---
- name: Create clickhouse-backup cronjob bash script
  template:
    src: cronjob-clickhouse-backup.sh.j2
    dest: "/usr/local/bin/cronjob-clickhouse-backup-{{ item }}.sh"
    owner: root
    group: root
    mode: '0775'
  loop:
    - daily
    - weekly
    - monthly

- name: Set default state for clickhouse-backup cron file
  set_fact:
    clickhouse_backup_crontab_state: absent

- name: Overwrite state for clickhouse-backup cron file
  set_fact:
    clickhouse_backup_crontab_state: present
  when: clickhouse_backup_install_crontab

- name: set default for set_fact
  set_fact:
    "{{ item }}_backup_status": present
  when: clickhouse_backup_install_crontab
  loop:
    - daily
    - weekly
    - monthly

- name: Overwrite state for clickhouse-backup-type in cron file
  set_fact:
    "{{ item }}_backup_status": absent
  when: "clickhouse_backup_general_backups_to_keep_remote_{{ item }} == 0"
  loop:
    - daily
    - weekly
    - monthly

- name: Creates/remove cron file under /etc/cron.d
  cron:
    name: Add cronjob for clickhouse backup
    special_time: "{{ item.time }}"
    user: root
    job: "/usr/local/bin/cronjob-clickhouse-backup-{{ item.time }}.sh"
    cron_file: "clickhouse-backup-{{ item.time }}"
    state: "{{ item.clickhouse_backup_crontab_state }}"
  loop:
    - { time: 'daily' , clickhouse_backup_crontab_state: '{{ daily_backup_status }}' }
    - { time: 'weekly' , clickhouse_backup_crontab_state: '{{ weekly_backup_status }}' }
    - { time: 'monthly' , clickhouse_backup_crontab_state: '{{ monthly_backup_status }}' }

- name: copy local backup removal script
  copy:
    src: remove-clickhouse-local-backups.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 775
    force: yes
  tags: backup_removal

- name: Remove local backups via cron job
  cron:
    name: Add cronjob for remove local backups
    hour: '{{ clickhouse_backup_local_removal_hour }}'
    user: root
    job: /usr/local/bin/remove-clickhouse-local-backups.sh
    cron_file: "remove-clickhouse-local-backup"
  when: clickhouse_backup_general_backups_to_keep_local == 0
  tags: backup_removal

  