---
- set_fact:
    backup_name: "molecule_backup_{{ ansible_hostname }}{{ lookup('pipe','date -u +%Y-%m-%d') }}"

- name: Upload backup
  shell: "clickhouse-backup  -c /etc/clickhouse-backup/config-daily.yml upload {{ backup_name }}"
  register: backup_upload

- name: Verify backup upload return code
  assert:
    that:
      - backup_upload.rc == 0
